<?php

namespace AppBundle\Repository;

/**
 * BridgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BridgetRepository extends \Doctrine\ORM\EntityRepository
{
}
