<?php

namespace AppBundle\Repository;

/**
 * CompteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNoInstalled()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM AppBundle:Compteur c WHERE c.isInstalled = '0'")
            ->getResult();
    }
}
