<?php

namespace AppBundle\Repository;

/**
 * devisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class devisRepository extends \Doctrine\ORM\EntityRepository
{
}
