<?php

namespace AppBundle\Repository;

/**
 * FournisseurCompteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurCompteurRepository extends \Doctrine\ORM\EntityRepository
{
}
