<?php

namespace AppBundle\Repository;

/**
 * infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class infoRepository extends \Doctrine\ORM\EntityRepository
{
}
