<?php

namespace AppBundle\Repository;

/**
 * LotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LotRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLotsById($id){
        $fields = array('l.id', 'l.numero', 'l.etage','l.surface','l.tantieme', 'l.reference','l.photo');
        return $this->createQueryBuilder('l')
            ->select($fields)
            ->andWhere('l.appartement = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult()
            ;
    }

    public function findLotsByAdresseAndId($adresse,$id){
        $fields = array('l.id', 'l.numero', 'l.surface', 'l.etage','l.photo','l.tantieme');
        return $this->createQueryBuilder('l')
            ->select($fields)
            ->where('l.appartement=:id')
            ->setParameter('id',$id)
            ->andWhere('l.numero LIKE :adresse')
            ->setParameter('adresse', '%'.$adresse.'%')
            ->getQuery()
            ->getResult()
            ;
    }
}
