<?php

namespace AppBundle\Repository;

/**
 * MesureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesureRepository extends \Doctrine\ORM\EntityRepository
{
}
