<?php

namespace AppBundle\Repository;

/**
 * RadiateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadiateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRadiateurBycalorimetre($compteur)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT r FROM AppBundle:Radiateur r WHERE r.calorimetre = $compteur")
            ->getResult();
    }
}
