<?php

namespace AppBundle\Repository;

/**
 * TypeCompteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompteurRepository extends \Doctrine\ORM\EntityRepository
{

}
